export const ADD_TO_CART_LOADING="ADD_TO_CART_LOADING"
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_ERROR="ADD_TO_CART_ERROR"

export const DELETE_PIZZA_LOADING="DELETE_PIZZA_LOADING"
export const DELETE_PIZZA_SUCCESS="DELETE_PIZZA_SUCCESS"
export const DELETE_PIZZA_ERROR="DELETE_PIZZA_ERROR"

